export const CLEAR_SELECTED_PLAYERS = "CLEAR_SELECTED_PLAYERS";
export const GET_TOURNAMENT_DATA = 'GET_TOURNAMENT_DATA';
export const GET_TOURNAMENT_DATA_ERROR = 'GET_TOURNAMENT_DATA_ERROR';
export const SET_ALL_PLAYER_NAMES = 'SET_ALL_PLAYER_NAMES';
export const SET_SELECTED_PLAYERS = 'SET_SELECTED_PLAYERS';
export const SET_SELECTED_PLAYERS_ERROR = 'SET_SELECTED_PLAYERS_ERROR';
export const SET_TIME_ZONE = "SET_TIME_ZONE";
export const SHOW_SIGN_UP_FORM = "SHOW_SIGN_UP_FORM";
export const SHOW_SIGN_UP_FORM_ERROR = "SHOW_SIGN_UP_FORM_ERROR";
export const TOGGLE_SHOW_HISTORY = "TOGGLE_SHOW_HISTORY";

export const LAMBDA_URI = "/.netlify/functions";
