export const GET_TOURNAMENT_DATA = 'GET_TOURNAMENT_DATA';
export const GET_TOURNAMENT_DATA_ERROR = 'GET_TOURNAMENT_DATA_ERROR';
export const SET_ALL_PLAYER_NAMES = 'SET_ALL_PLAYER_NAMES';
export const SET_SELECTED_PLAYERS = 'SET_SELECTED_PLAYERS';
export const SET_SELECTED_PLAYERS_ERROR = 'SET_SELECTED_PLAYERS_ERROR';
